cols={
    'Cts.':'Size',
    'color':'Color',
    'size':'Size',
    'shape':'Shape',
    'clarity':'Clarity',
    'COLOR':'Color',
    'SIZE':'Size',
    'SHAPE':'Shape',
    'CLARITY':'Clarity',
    'CTS.':'Size',
    'Item Code':'ItemCD',

}


shapes= {
        #Radiant
        'Cut-Cornered Rectangular Mod Br': 'Radiant',
        'CUT-CORNERED RECTANGULAER MODIFIEDBRILLIANT':'Radiant',
        'Cut-Cornered Rectangular Modified Br': 'Radiant',
        'Round-Cornered Rectangular Modified Br': 'Radiant',
        'ROUND-CORNERED RECTANGULAR MODIFIEDBRILLIANT': 'Radiant',
        'CUT CORN RACT MODI BRILLI': 'Radiant',
        'CUT CORNER RECTAMODI BRILL': 'Radiant',        
        'rediant': 'Radiant',
        'redian': 'Radiant',
        'rectmod': 'Radiant',
        'rectangular modified brilliant': 'Radiant',
        'Cut-Cornered Rectangular Mod Br': 'Radiant',
        'Cut corneredrectangular mod brill': 'Radiant',
        'CUT-CORNERED RECTANGULAR MOD BR': 'Radiant',
        'Cut-Cornered Rectangular M.B': 'Radiant',
        'CUT CORNERED RECTANGULAR MODI BR': 'Radiant',
        'CUT CORNERED RECTANGULARMODIFIED BRILLIANT.': 'Radiant',
        '-CUT-CORNERED RECTANGULAR MODIFIED': 'Radiant',
        'CUT CORNERED RECTANGULARMODIFIED BRILLIANT ': 'Radiant',
        'CUT- CORNERED RECTANGULAR MODIFIEDBRILLIANT': 'Radiant',
        'CUT Cornered Rectangular ModifiedJ': 'Radiant',
        'CUT-CORNERED RECTANGULAR M.B.': 'Radiant',
        'CUT CORNERED RECTANGULAR MODIFIED': 'Radiant',
        'CUT-CORNERED RECTANGULAR MODIFIEDBRILLIANT': 'Radiant',
        'CUT CORNERED RECTANGULAR MODIFIEDBRILLIANT': 'Radiant',           
        'cut cornred rectan modi bri': 'Radiant',
        'CUT-CORNERED RECTANGULARMODIFIED BRILLIANT': 'Radiant',
        'Cut Cornered Rectangular ModifiedBrilliant':'Radiant',
        'CUT CORNERED RECTANGULAR MOD.BRILLIANT': 'Radiant',
        'Cut Cornered Rectangular MB': 'Radiant',
        'CUT - CORNERD RECTANGULAR MODIFIEDBRILLIANT': 'Radiant',
        'CUT CORNERED RECTANGULAR MODIFIEDBRILLIANT': 'Radiant',
        'Cut-Cornered Rectangular ModifiedBrilliant': 'Radiant',
        'cut-cornered rectangular modified brilliant': 'Radiant',
        'CUT-CORNERED RECTANGULAR MODIFIELD BRILLIANT': 'Radiant',
        'CUT-CORNERED RECTANGULAR M. B ': 'Radiant',
        'CUT-CORNERED RECTANGULAR M. B. ': 'Radiant',
        'C.C RECTANGULAR MODIFIED BRILLIANT': 'Radiant',
        'CUTCORNERED RECTANGULAR MODIFIED BRILLIANT': 'Radiant',
        'ROUND-CORNERED RECTANGULAR MODIFIED BRILLIANT': 'Radiant',
        'Round-Cornered Rectangular Modified BRILLIANT': 'Radiant',
        'CORNERED RECTANGULAR MODIFIED BRILLIANT': 'Radiant',
        'Cornered Rectangular Modified BRILLIANT': 'Radiant',
        'CUT-CORNEREDRECTANGULAR MODIFIED BRILLIANT': 'Radiant',
        'Cut-CorneredRectangular Modified Brilliant': 'Radiant',
        'recta modi brill': 'Radiant',
        'rcrmb': 'Radiant',
        'r m b': 'Radiant',
        'radiant': 'Radiant',
        'r.m.b.': 'Radiant',
        'crmb': 'Radiant',
        'corn rect modi brillant': 'Radiant',
        'cut-cornered rectangular modified brilli': 'Radiant',
        'correctangular modi brill': 'Radiant', 
        'cccrmb': 'Radiant',
        'c.c.rm.b': 'Radiant',
        'ccrmb': 'Radiant',
        'c.c.r.m.b.': 'Radiant',
        'c.c.r.m.b': 'Radiant',
        'c r m b': 'Radiant',
        'c c r m b': 'Radiant',
        'rcrb': 'Radiant',
        'RAD': 'Radiant',
        'RACTANGULAR MODIFIED BRILLIANT': 'Radiant',
        'RECTANGULER MODIFIED BRILLIANT': 'Radiant',
        'CUT CORNERED RECTANGUKAR MODIFIED BRILLIANT': 'Radiant',
        'Cut Cornered Rectanulare Modified Brilliant':'Radiant',
        'L RADIANT':'Radiant', 
        'RN':'Radiant', 
        'RADIANT':'Radiant',
        'RCRB': 'Radiant',
        'Cut-Cornered Rectangular Modified': 'Radiant',
        'RAD':'Radiant',

        #Marquise
        'mq b': 'Marquise ',
        'marquise brilliant': 'Marquise ',
        'mrqs br': 'Marquise',
        'mrqs': 'Marquise',
        'modified marquise step cut': 'Marquise Step Cut',
        'mmb': 'Marquise ',
        'mqb': 'Marquise',
        'm.m.b.':'Marquise ',
        'marquisebrilliant': 'Marquise',
        'marquise': 'Marquise',
        'marquiese': 'Marquise',
        'marquese': 'Marquise',
        'marq': 'Marquise',
        'MRQ': 'Marquise',
        'mq': 'Marquise',
        'Mq.Br': 'Marquise',
        'mb': 'Marquise',
        'MODIFIED MARQUISE STEP CUT': 'Marquise Step Cut',
        'MARQUISE MODIFIED BRILLIANT': 'Marquise',
        'Marquise Modified Brilliant': 'Marquise',
        'MARQUISE':'Marquise', 
        'MQ':'Marquise',

        #tapered baguette
        'tapered baguette': 'Tapered Baguette',
        'tapered baguette': 'Tapered Baguette',
        'buguette': 'Tapered Baguette',
        'bug': 'Tapered Baguette',
        'bgts': 'Tapered Baguette',
        'baguettes': 'Tapered Baguette',
        'baguette': 'Tapered Baguette',
        'tb': 'Tapered Baguette',
        'bg': 'Tapered Baguette',
        'TP':'Tapered Baguette',

        #Trapezoid
        'TSC':'Trapezoid Step Cut',
        'trapez step cut': 'Trapezoid Step Cut',
        'TRAPEZOIDSTEP CUT': 'Trapezoid Step Cut',
        'TRAPEZOID BRILLAINT': 'Trapezoid Brilliant',
        'CUT-CORNERED TRAPEZOID PORTRAIT': 'Cut-Cornered Trapezoid Portrait',
        'trapezoid': 'TRAPEZOID',
        'trapeziod': 'TRAPEZOID',
        'trapeze': 'TRAPEZOID',
        'TRAPEZOID MODIFIED BRILLIANT': 'TRAPEZOID ',
        'Trapezoid Mixed Cut': 'Trapezoid Mixed Cut',
        'trapezoid step cut': 'Trapezoid Step Cut', 
        'TRAPEZOID STEPCUT': 'Trapezoid Step Cut',   
        'trapexoid': 'TRAPEZOID',
        'TPZ':'	Trapezoid Step Cut',

        #Pentagonal
        'Modified Pentagontal Step CutEM': 'Pentagonal Step Cut',
        'Modified Pentagonal Mixed Cut': '	Modified Pentagonal Mixed Cut',

         #triangular   
        'MODI. TRIAN.BRILL':'Triangular',
        'triangular': 'Triangular',
        'C.C.T.Step Cut ':'Cut Cornered Triangular Step Cut',
        'Cut-Cornered Triangular Mixed Cu':'Triangular Mixed Cut',
        'triangula': 'Triangular',
        'MODI. TRIANGULAR BRILL': ' Triangular',
        'TRIANGULAR STEP CUT': 'Triangular Step Cut',
        'MODIFIED TRIANGULAR STEP CUT': 'Triangular Step',
        'MTSC': 'Triangular Step Cut',
        'ROUND-CORNERED TRIANGULAR MODIFIED BRILLIANT': 'Round-Cornered Triangular Modified Brilliant',
        'TRIANGULAR MODIFIED BRILLIANT': 'Triangular',
        'CUT-CORNERED TRIANGULAR STEP CUT': 'Triangular Step Cut',
        'triangle': 'TRIANGLE',
        'MIX MODI. TRIANGULARMIX CUT': 'Mix Modified Triangular',
        'mtb': 'Triangular',
        'modified triangular brilliant': 'Triangular ',
        'modified triangular': 'Triangular modified ',
        'cut-cornered triangular step': 'Triangular step Cut',
        'cut-cornered triangular step cut': 'Triangular step cut',
        'Cut-Cornered Triangular StepCut': 'Triangular step Cut',
        'CCTST': 'Triangular Step Cut',
        'cctst': 'Triangular Step Cut',
        'cctsc': 'Triangular Step Cut',
        'asismarquis': 'Triangular Step',
        'Triangular Step Cut': 'Triangular Step Cut',

        #princess
        'square modified brilliant': 'Princess',
        'Square Modified Brilliant': 'Princess',
        'Square Modified Brillian': 'Princess',
        'Square Modified Br': 'Princess',
        'SQUARE MODIFIED BR': 'Princess',
        'SQUARE MODIFIED BR': 'Princess',
        'SQUARE MOD.BR.': 'Princess',
        'Sq M. Br': 'Princess',
        'Sq M B': 'Princess',
        'M SQ BR': 'Princess',
        'SQUARE MOD.BRI.': 'Princess',
        'CUT CORNER SQUAREMODI BRILL': 'Princess',
        'SQ. M.B': 'Princess',
        'Sq.M.Br.' : 'Princess',
        'smb(princess)': 'Princess',
        'smb': 'Princess',
        's.m.b.': 'Princess',
        's.m.b': 'Princess',
        's m b': 'Princess',
        'princess': 'Princess',
        'msbf': 'Princess',
        'msbd': 'Princess',
        'msb': 'Princess',
        'cutprincess': 'Princess',
        'csmb': 'Princess',
        'square mb': 'Princess',
        'square modi br': 'Princess',
        'corsquare modi brill': 'Princess',
        'ccsmb': 'Princess',
        'Square ModifiedBrilliant': 'Princess',
        'Sq.M.Br': 'Princess',
        'Sq.M.B.':'Princess',
        'PC': 'Princess ',
        'MODIFIED SQUAREBRILLIANT':'Princess',
        'SQ MODIFIEDBRILLIANT': 'Princess',
        'SQUAREMODIFIED BRILLIANT': 'Princess',
        'PC': 'PRINCESS',
        'SQ': 'PRINCESS',

        #Emerald
        'square emerald cut': 'Square Emerald',
        'SQUARE EMRLAD CUT': 'Square Emerald',
        'square emerald': 'Square Emerald',
        'sq emerald': 'Square Emerald',
        'sq.emerald': 'Square Emerald',
        'SQ.EMERALD CUT':'Square Emerald',
        'EMERALD CUT SQUARE':'Square Emerald',
        'sq. em': 'Square Emerald',
        'sqem': 'Square Emerald',
        'sq em': 'Square Emerald',
        'sem': 'Square Emerald',
        'sec': 'Square Emerald',
        'SQ EMERALD':'Square Emerald', 
        'SQUARE EMERALD':'Square Emerald',
        'em c':'Emerald',
        'emerald cut': 'Emerald',
        'emrald': 'Emerald',
        'emeraldwhite': 'Emerald',
        'emerald brilliant': 'Emerald',
        'emarald cut': 'Emerald',
        'emerald': 'Emerald',
        'eme': 'Emerald',
        'emd': 'Emerald',
        'emb': 'Emerald',
        'cut em': 'Emerald',
        'cutemeralds': 'Emerald',
        'cutemerald': 'Emerald',
        'EC':'Emerald',
        'em': 'Emerald',
        'ec': 'Emerald',
        'EM':'Emerald', 
        'EMERALD':'Emerald',
        'EM': 'Emerald',

        #cushion
        'square cushion brilliant': 'Square Cushion Brilliant',
        'SQ. CUSHION MODIFIED BRILLIANT': 'Square Cushion Modified Brilliant',
        'modified brilliant cushion': 'Cushion',
        'long cushion': 'Long Cushion',
        'Cushion MixedCut': 'Cushion Mixed Cut',
        'cushion mixed cut': 'Cushion Mixed Cut',
        'cushionwhite': 'Cushion',
        'SQUARE CUSHION MODIFIED BRILLIANT': 'Square Cushion Modifeid Brilliant',
        'cushionmodified brilliant': 'Cushion ',
        'cushion modified brilliant': 'Cushion ',
        'cushion modified': 'Cushion modified',
        'cushion modi brill': 'Cushion ',
        'cushion modi br': 'Cushion ',
        'cushion brilliant': 'Cushion',
        'cushion': 'Cushion',
        'cush modi brillnatural': 'Cushion ',
        'cumbr': 'Cushion ',
        'cumb': 'Cushion ',

        'cum': 'Cushion modified',
        'cushion m.br': 'Cushion ',
        'cmb(cushion)': 'Cushion',
        'cmb(cushion )': 'Cushion ',
        'cus modfied brill': 'Cushion',
        'CUS MOD BRIL ':'Cushion',
        'CUSH MOD BRIL ':'Cushion',
        'cmb': 'Cushion',
        'CUSION MODIFIED BRILLIANT':'Cushion',
        'cu.m.b.': 'Cushion',
        'cushion mb': 'Cushion',
        'C.M.B': 'Cushion ',
        'cushion mbr': 'Cushion',
        'cushion modi.brilliant': 'Cushion',
        'cu.m.b': 'Cushion',
        'partially faceted cushion': 'PARTIALLY FACETED CUSHION',
        'c.m.b.': 'Cushion',
        'cus mod br.':'Cushion',
        'cus mod br': 'Cushion',
        'modified brilliant cushion': 'Cushion',
        'cushion modi.brill': 'Cushion',
        'cushion modi br': 'Cushion',
        'cushion m. br': 'Cushion ',
        'c m b': 'Cushion',
        'cm': 'Cushion Modified',
        'cb': 'Cushion',
        'cu': 'Cushion',
        'c b': 'Cushion',
        'CM Briliant': 'Cushion',
        'Cushion MB': 'Cushion',
        'CUSHION MODIFIED BRILLANT': 'Cushion',
        'Cushion ModifiedBrilliant': 'Cushion',
        'CUSHION STEP CUT': 'Cushion Step Cut',
        'CMB': 'Cushion Modified',
        'CB': 'Cushion',
        'CU':'Cushion',
        'CS':'Cushion Modified', 
        'CUSHION MODIFIED':'Cushion Modified',
        'CUSHION BRILLIANT':'Cushion Brilliant',

        #Oval
        'OVAL MODI BRILL': 'Oval ',
        'ovm': 'Oval ',
        'ovals': 'Oval',
        'ovalh': 'Oval',
        'oval rose cut': 'OVAL ROSE CUT',
        'oval modified brilliant': 'Oval',
        'oval brilliant': 'Oval',
        'oval b': 'Oval',
        'oval': 'Oval',
        'omb': 'Oval ',
        'obf': 'Oval',
        'o.m.b.': 'Oval ',
        'mosc': 'Oval Step Cut',
        'modified oval step cut': 'Oval Step Cut',
        'oval step cut': 'Oval Step Cut',
        'cutovals': 'Oval',
        'cutoval': 'Oval',
        'modified oval step cut': 'Oval Step Cut',
        'oval modified step cut': 'Oval Step Cut',
        'oval step cut': 'Oval Step Cut',
        'ob': 'Oval',
        'ol': 'Oval',
        'Ov.Br.': 'Oval',
        'ov': 'Oval',
        'STEP OVAL': 'Oval Step Cut',
        'MODIFIED OVAL STEP CUT': 'Oval Step Cut',
        'OVAL MODIFIEDBRILLIANT ': 'Oval',
        'OV':'Oval',
        'OVB':'Oval',
        'OB':'Oval',
        'OVM':'Oval',
        'OV':'Oval',
        'OVAL':'Oval',
        'OB':'Oval',
        'Oval Brilliant':'Oval',

        #heart
        'HEART MODI BRILLVS2': 'Heart',
        'hrt': 'Heart',
        'hmb': 'Heart',
        'heartshape': 'Heart',
        'heart modified brilliant': 'Heart',
        'heart b': 'Heart',
        'ht b': 'Heart',
        'hb(heart)': 'Heart',
        'ht bri': 'Heart',
        'heartmodified': 'Heart Modified',
        'heart brilliant': 'Heart',
        'heart': 'Heart',
        'hbc': 'Heart',
        'HE.Br': 'Heart',
        'hb': 'Heart',
        'ht': 'Heart',
        'he': 'Heart',
        'HEART ROSE CUT': 'Heart Rose Cut',
        'HT':'Heart',
        'HEART':'Heart',
        'HTM': 'Heart',
        'HT': 'Heart',
        'HTB': 'Heart',
        'HMB': 'Heart',

        #pear
        'PR':'Pear',
        'pr':'Pear',
        'PEAR MODI BRILL': 'Pear ',
        'PEARMODI BRILL': 'Pear ',
        'PEAR MODIFIEDBRILLIANT':'Pear',
        'pmb': 'Pear ',
        'pears': 'Pear',
        'pearh': 'Pear',
        'pear modified brilliant': 'Pear',
        'pear brilliant': 'Pear',
        'pe b': 'Pear',
        'pear': 'Pear',
        'pbe': 'Pear',
        'pbc': 'Pear',
        'p.m.b.': 'Pear ',
        'p.m.b': 'Pear ',
        'mpb': 'Pear ',
        'modified peer step cut': 'Pear Step Cut',
        'modified pear step cut': 'Pear Step Cut',
        'modified pear modified step cut': 'Pear Step Cut',
        'modified pear brilliant': 'Pear ',
        'modified pear': 'Pear modified',
        'pear step cut': 'Pear Step Cut',
        'cutpears': 'Pear',
        'cutpear': 'Pear',
        'modified peer step cut': 'Pear Step Cut',
        'modified pear step cut': 'Pear Step Cut',
        'pear modified step cut': 'Pear Step Cut',
        'modified pear modified step cut': 'Pear Step Cut',
        'modified pear brilliant': 'Pear ',
        'pear step cut': 'Pear Step Cut',
        'treatedpear mb':'PEAR',
        'PE.BR.': 'Pear',
        'pb': 'Pear',
        'ps': 'Pear',
        'pe': 'Pear',
        'PB/CUT': 'Pear',
        'STEP PEARL': 'Pear Step Cut',
        'MODIFIED PEAR STEP CUT': 'Pear Step Cut',
        'PEARMODIFIED BRILLIANT': 'Pear',
        ' PEARS MODIFIED  BRILLIANT': 'Pear',
        'PS':'Pear',
        'PB':'Pear',
        'PEAR BRILLIANT':'Pear',
        'Pear Brilliant':'Pear',
        'Pear Modified': 'Pear',
        'PSM': 'Pear',
        'PSB': 'Pear',
        'PB': 'Pear',
        'PS': 'Pear',
     

        #square
        'Square Step Cut': 'Square Step Cut',
        'SQUARE STEP CUT': 'Square Step Cut',
        'SSC': 'Square Step Cut',
        'square': 'Square',
        'modified square step cut': 'Square Step Cut',
        'square modified step cut': 'Square Step Cut',
        'modified square step cut': 'Square Step Cut',
        'square modified step cut': 'Square Step Cut',
        'carre cut': 'Square Step Cut',
        'c brl': 'Square',
        'sq': 'Square',
        'Sqaure modified Brilliant':'Princess',
        'Cut-Cornered Square Step': 'Square Step Cut',

        #rectangular
        'rsc': 'Rectangular Step Cut',
        'rectangular step cut': 'Rectangular Step Cut',
        'RECTANGULAR STEPCUT': 'Rectangular Step Cut',
        'rectangular': 'Rectangular',
        'ractungular': 'Rectangular', 
        'modified rectangular step cut': 'Rectangular Step Cut',
        'rectangular modified step cut': 'Rectangular Step Cut',
        'modified rectangular step cut': 'Rectangular Step Cut',
        'rectangular modified step cut': 'Rectangular Step Cut',
        'ccrmc': 'Cut-Cornered Rectangular Mixed Cut',
        'CCR MIXED CUT': 'Cut-Cornered Rectangular Mixed Cut',
        'CUT-CORNERED RECTANGULAR MIXED CUTI': 'Cut-Cornered Rectangular Mixed Cut',
        'ccrm': 'Cut-Cornered Rectangular Mixed Cut',
        'C.C.R.M.C.': 'Rectangular Mixed Cut',
        ' Mod. Rectangle steps cut':'Rectangular Step Cut',
        'Rectangular Modified Brilliant': 'Rectangular',
        'RECT': 'Rectangular',
        'LPS': 'Rectangular',
        'Cut-Cornered Rectangular Mixed': 'Rectangular Mixed',

        # new shape 
        'trillion': 'Trillion',
        'trilliant': 'Trillion',
        'rectangualr portraith': 'Cut-Cornered Rectangular Portrait Cut',
        'shield': 'Shield',
        'teppar': 'Teppar',
        'tapper': 'Tapered',
        'taper': 'Tapered',
        'starbrilliant': 'Modified Star Brilliant',
        'star br': 'Modified Star Brilliant',
        'omc': 'Old European',
        'oldeuropean': 'Old European',
        'old mine br': 'Old Mine',
        'old mine brilliant': 'Old Mine',
        'old mine': 'Old Mine',
        'old europeanbrilliant': 'Old European',
        'old european brilliant': 'Old European',
        'old european': 'Old European',
        'old eu br': 'Old European ',
        'old eu': 'Old European',
        'oeb': 'Old European',
        'octagonal step cut': 'Octagonal Step Cut',
        'octagon': 'Octagon',
        'moon': 'Half-Moon',
        'Modified Half-Moon Brilliant':'Half-Moon Modified Brilliant',
        'modified shield step': 'Shield Step',
        'modified shield ste': 'Shield Step',
        'FREEFORM FACETED': 'FREEFORM FACETED',
        'modified shield step cut': 'Shield Step Cut',
        'lozenge mixed cut': 'Lozenge mixed cut',
        'lozenge step cut': 'Lozenge step cut',
        'lozenge': 'Lozenge step cut',
        'kite': 'Kite Step Cut',
        'Kite Mixed Cut': 'Kite Mixed Cut',
        'MKSC':'Kite Step Cut',
        'KT': 'Modified Kite Step',
        'HEXAGONAL BRILLIANT': 'Hexagon',
        'Hexagonal Mixed Cut': 'Hexagon Mixed Cut',
        'Hexagonal MixedCut': 'Hexagon Mixed Cut',
        'hexagonal': 'Hexagon Step Cut',
        'hexagona': 'Hexagon Step Cut',
        'hexagon': 'Hexagon Step Cut',
        'horse' : 'Horse',
        'halfmoon': 'Half Moon',
        'Half -Moon Step Cut': 'Half Moon Step Cut',
        'HALF-MOON STEP CUT': 'Half Moon Step Cut',
        'Halfmoon Modified Brilliant': 'Half Moon',
        'Modified Half-Moon BrilliantF':'Half-Moon Modified Brilliant',
        'Modified Half-Moon BrilliantG':'Half-Moon Modified Brilliant',
        'Modified Half-Moon Brilliant':'Half-Moon Modified Brilliant',
        'flower modifiedbrilliant': 'Flower',
        'flame': 'Flame Step Cut',
        'Modified Flame': 'Flame Step Cut',
        'fish novelty': ' Fish Novelty',
        'novelty': 'NOVELTY',
        'modified shield step cut': 'Shield Step Cut',
        'shield modified step cut': 'Shield Step Cut',
        'modi tri rose. rose cut': ' Trigonal Rose Cut',
        'cadillac': 'Cadillac',
        'mssc':'Shield Step Cut',
        'butterfly step': 'BUTTERFLY STEP',
        'BUTTERFLY MIXED CUT ': 'BUTTERFLY MIXED CUT',
        'basis baguette':'Rectangular Step Cut', 
        'BRIOLETTE':'Briolette',
        'asscher': 'Asscher',
        'ASSCHER':'Asscher',
        'AS': 'Asscher',
        'leonardo da vinci cuttm': 'LEONARDO DA VINCI CUTTM', 
        'ROUND ROSE CUT': 'Round Rose Cut', 
        'Modified ShieldBrilliant': 'Shield',
        'Modified ShieldMixed Cut': 'Modified Shield Mixed Cut',
        'Modified Star Brilliant':'Star',
        'Novelty Modified Brilliant':'Novelty Modified Brilliant',
        'Novelty Brilliant':'Novelty',
        'Star Modified Brilliant': 'Star',
        'HALF-MOON MODIFIED BRILLIANT': 'Half-Moon Modified Brilliant',
        'MODIFIED LOZENGE STEP CUT': 'Lozenge Step Cut',
        'DECAGONAL MODIFIED BRILLIANT': 'Decagonal',
        'HORSE MODIFIED BRILLIANT': 'Horse Modified Brilliant',
        'MODIFIED LOZENGE BRILLIANT': 'Lozenge Modified Brilliant',
        ' Butterfly Modified Brilliant': 'Butterfly Modified Brilliant',
        'Flower Modified Brilliant': 'Flower Modified Brilliant',
        'Cat Modified Brilliant': 'Cat Modified Brilliant',
        'Modified Star Brilliant': 'Star Modified Brilliant',
        'SC': 'Square Step Cut',
        'SHMB': 'Modified Shield Step',
        'TS': 'Traingular Step Cut',

        #Round
        'roundwhite': 'Round',
        'rounds': 'Round',
        'roundbrilliant': 'Round ',
        'round brilliant': 'Round ',
        'round': 'Round',
        'rnd.': 'Round',
        'rnd': 'Round',
        'rmb': 'Round ',
        'round modified brilliant': 'Round',
        'rbc': 'Round',
        'r.b.': 'Round',
        'r white': 'Round',
        'r b': 'Round',
        'round step cut': 'Round Step Cut',
        'cutround': 'Round',
        'cutrbc': 'Round',
        'brc': 'Round',
        'rd': 'Round',
        'brilliant': 'Round',
        'rb': 'Round',
        'br': 'Round',
        'mrb': 'Round',
        'RD':'Round',
        'RO':'Round',
        'ROUND':'Round',
        'RD':'Round',
        


        #normalize
        'ROUND':'Round',
        'round':'Round',
        'PEAR':'Pear',
        'pear':'Pear',
        'CUSHION MODIFIED':'Cushion Modified',
        'OVAL':'Oval',
        'oval':'Oval',
        'EMERALD':'Emerald',
        'emerald':'Emerald',
        'PRINCESS':'Princess',
        'princess':'Princess',
        'RADIANT':'Radiant',
        'radiant':'Radiant',
        'HEART':'Heart',
        'heart':'Heart',
        'CUSHION':'Cushion',
        'cushion':'Cushiion',
        'TRAPEZOID':'Trapezoid',
        'trapezoid':'Trapezoid',
        'MARQUISE':'Marquise',
        'marquise':'Marquise',
        'TAPERED BAGUETTE':'Tapered Baguette',
        'tapered baguette':'Tapered Baguette',

        }

color={

            'Y - Z': 'YZ',
            'V L P': 'VLP',
            'FC B': 'FB',
            'F BRH P': 'F BR P',
            'FV Y': 'FVY',
            'F B Y': 'F BR Y',
            'Fancy Yellow': 'FY',
            'Fancy Deep Yellow-Brown': 'F DE Y B',
            'Fancy Dark Brown-Purple': 'F DA B P',
            'FC Y': 'FY',
            'FI Y': 'FIY',
            'FL P': 'FLP',
            'FC O P ': 'F O P',
            'FC O P': 'F O P',
            'FL Y': 'FLY',
            'L P': 'FLP',
            'L B': 'FLB',
            'F L B': 'FLB',
            'FL B': 'FLB',
            'F O P': 'F OY P',
            'F B':'FB',
            'F I Y':'FIY',
            'F V Y ':'FVY',
            'F L Y':'FLY',
            'F Y':'FY',
            'V L B':'VLB',
            'F I B':'FIB',
            'F I P':'FIP',
            'FNT B':'FB',
            'FNT P':'FP',
            'FL B':'FLB',
            'op': 'OP',
            'o-p': 'OP',
            'o to p': 'OP',
            'qr': 'QR', 
            'q-r': 'QR', 
            'q to r': 'QR',
            'st': 'ST', 
            's-t': 'ST', 
            's to t': 'ST',
            'uv': 'UV', 
            'u-v': 'UV', 
            'u to v': 'UV',
            'wx': 'WX', 
            'w-x': 'WX', 
            'w to x': 'WX',
            'yz': 'YZ', 
            'y-z': 'YZ', 
            'y to z': 'YZ',
            'deep brownish greenish yellow': 'FANCY DEEP BROWNISH GREENISH YELLOW',
            'deep grayish yellow dish green': 'FANCY DEEP GRAYISH YELLOWISH GREEN',
            'light grayish greenish yellow': 'FANCY LIGHT GRAYISH GREENISH YELLOW',
            'naturalfancy brownish greenish yeiiow': 'FANCY BROWNISH GREENISH YELLOW ',
            'deep brownish purple-pink': 'FANCY DEEP BROWNISH PURPLE-PINK',
            'deep brownish purple pink': 'FANCY DEEP BROWNISH PURPLE PINK',
            'DEEP BROWNISH YELLOWISH ORANGE,': 'FANCY DEEP BROWNISH YELLOWISH ORANGE',
            'DEEP GREEN TREATED COLOUR': 'FANCY DEEP GREEN TREATED COLOUR',
            'Deep Brownish Yellowish Orange': 'Fancy Deep Brownish Yellowish Orange',
            'fancy light yellow': 'FANCY LIGHT YELLOW',
            'intense yellow-green': 'FANCY INTENSE YELLOW-GREEN',
            'lightbrownish greenish yellow': 'FANCY LIGHT BROWNISH GREENISH YELLOW',
            'darkbrown-greenish yellow': 'FANCY DARK BROWN-GREENISH YELLOW',
            'deep brownish yellow': 'FANCY DEEP BROWNISH YELLOW',
            'deep orangy yellow': 'FANCY DEEP ORANGY YELLOW',
            'deep brownish orangey yellow': 'FANCY DEEP BROWNISH ORANGY YELLOW',
            'intense purplish pink': 'FANCY INTENSE PURPLISH PINK',
            'lightgrayish greenish yellow': 'FANCY LIGHT GRAYISH GREENISH YELLOW',
            'dark orangey brown': 'FANCY DARK ORANGEY BROWN',
            'intense orange yellow': 'FANCY INTENSE ORANGE YELLOW',
            'light brownish greenish yellow': 'FANCY LIGHT BROWNISH GREENISH YELLOW',
            'light yellowishbrown': 'FANCY LIGHT YELLOWISH BROWN',
            'lightpinkish brown': 'FANCY LIGHTPINKISH BROWN',
            'brownish greenish yellownatural even': 'FANCY BROWNISH GREENISH YELLOW NATURAL',
            'light brownish greenishyellow': 'FANCY LIGHT BROWNISH GREENISH YELLOW',
            'gray-greenish yellow': 'FANCY GRAY-GREENISH YELLOW',
            'brownish greenish yellownatural': 'FANCY BROWNISH GREENISH YELLOW',
            'vivid orange yellow': 'FANCY VIVID ORANGE YELLOW',
            'deep brownish orange': 'FANCY DEEP BROWNISH ORANGE',
            'deep yellowish orange': 'FANCY DEEP YELLOWISH ORANGE',
            'brownish orangy pink': 'FANCY BROWNISH ORANGY PINK',
            'intense yellowish orange': 'FANCY INTENSE YELLOWISH ORANGE',
            'grayish yellowish green': 'FANCY GRAYISH YELLOWISH GREEN',
            'deep  pink-purple': 'FANCY DEEP PINK-PURPLE',
            'vivid yellowish orange ': 'FANCY VIVID YELLOWISH ORANGE',
            'intense yellowish green': 'FANCY INTENSE YELLOWISH GREEN',
            'deep brownish orangyyellow': 'FANCY BROWNISH ORANGY YELLOW',
            'dark orangy browneven': 'FANCY DARK ORANGY BROWN',
            'brownish purple-pink': 'FANCY BROWNISH PURPLE-PINK',
            'light pinkish purple': 'FANCY LIGHT PINKISH PURPLE',
            'deep yellowish- orangesi': 'FANCY DEEP YELLOWISH ORANGESI',
            'deep grayish greenishyellow': 'FANCY DEEP GRAYISH GREENISHYELLOW',
            'fancy pinkish purple': 'FANCY FANCY PINKISH PURPLE',
            'brownish greenish yellow': 'FANCY BROWNISH GREENISH YELLOW',
            'light greenish yellow': 'FANCY LIGHT GREENISH YELLOW',
            'dark orangy brown': 'FANCY DARK ORANGY BROWN',
            'light yellow green': 'FANCY LIGHT YELLOW GREEN',
            'darkgray yellowish green': 'FANCY DARKGRAY YELLOWISH GREEN',
            'dark orange-brown': 'FANCY DARK ORANGE-BROWN',
            'intense orangy yellow': 'FANCY INTENSE ORANGY YELLOW',
            'brownish purplish pink': 'FANCY BROWNISH PURPLISH PINK',
            'brownish-greenish yellow': 'FANCY BROWNISH-GREENISH YELLOW',
            'grayish greenish yellow': 'FANCY GRAYISH GREENISH YELLOW',
            'dark green gray': 'FANCY DARK GREEN GRAY',
            'VERY LIGHT PINK': 'FANCY VERY LIGHT PINK',
            'VIVID YELLOW ORANGE': 'FANCY VIVID YELLOW ORANGE',
            'N.F.BROWNISHGR. YELL.':'Fancy Brownish Greenish Yellow',
            'MediumYellow': 'FANCY MEDIUM YELLOW',
            'FNCY DEP BROWNSGRENSH YELW':'FANCY DEEP BROWNISH GREENISH YELLOW',
            'FNCY DEP BROWNSORANGY YELW':'FANCY DEEP BROWNISH ORANGY YELLOW',
            'Fancy Brownish Pink': 'FANCY BROWNISH PINK',
            'FNCY DRKBROWN-GRENSH YELW':'FANCY DARK BROWN-GREENISH YELLOW',
            'FNCY DRK GRENSHBROWN': 'FANCY DARK GREEN-BROWN',
            'FNCY DEP BROWNSYELW':'FANCY DEEP BROWNISH YELLOW',
            'Fan Yell': 'FANCY YELLOW',
            'Fan Lig Yell': 'FANCY LIGHT YELLOW',
            'K MediumYellow': 'FANCY MEDIUM YELLOW',
            'F.D.O.B': 'FANCY DEEP ORANGE BROWN',
            'INTENSE YELLOW ORANGE': 'FANCY INTENSE YELLOW ORANGE',
            'LIGHT YELLOWISH BROWN': 'FANCY LIGHT YELLOWISH BROWN',
            'deep orange yellow': 'FANCY DEEP ORANGE YELLOW',
            'DEEP GREEN-YELLOW':'FANCY DEEP GREEN-YELLOW',
            'light pinkish brown': 'FANCY LIGHT PINKISH BROWN',
            'dark gray yellowishgreen': 'FANCY DARK GRAY YELLOWISHGREEN',
            'light green yellow': 'FANCY LIGHT GREEN YELLOW',
            'light yellow green': 'FANCY LIGHT YELLOW GREEN',
            'DEEPBROWNISH YELLOWISH ORANGE': 'FANCY DEEPBROWNISH YELLOWISH ORANGE',
            'FancyGrayish Yellowish Gree': 'FancyGrayish Yellowish Gree',
            'DEEP BROWNISHYELLOWISH ORANGE': 'FANCY DEEP BROWNISHYELLOWISH ORANGE',
            'LIGHT BLUISH GREEN': 'FANCY LIGHT BLUISH GREEN',
            'LIGHT PINK': 'FANCY LIGHT PINK',
            'INTENSE BLUE': 'FANCY INTENSE BLUE',
            'PINKISH PURPLE': 'FANCY PINKISH PURPLE',
            'PINK PURPLE': 'FANCY PINK PURPLE',
            'PINK BROWN': 'FANCY PINK BROWN',
            'INTENSE YELLOW ORANGE': 'FANCY INTENSE YELLOW ORANGE',
            'DEEP BROWNISH ORANGY YELLOW': 'FANCY DEEP BROWNISH ORANGY YELLOW',
            'DEEP BLUISH GREEN': 'FANCY DEEP BLUISH GREEN',
            'VIVID YELLOW-ORANGE': 'FANCY VIVID YELLOW-ORANGE',
            'VERY LIGHT GREEN': 'FANCY VERY LIGHT GREEN',
            'VIVID PURPLISH PINK': 'FANCY VIVID PURPLISH PINK',
            'YELLOWISH GREEN': 'FANCY YELLOWISH GREEN',
            'VERY LIGHT YELLOW GREEN': 'FANCY VERY LIGHT YELLOW GREEN',
            'LIGHT PINK-BROWN': 'FANCY LIGHT PINK-BROWN',
            'MEDIUM BLUE': 'FANCY MEDIUM BLUE',
            'VIVID BLUE,': 'FANCY VIVID BLUE',
            'VIVID BLUE': 'FANCY VIVID BLUE',
            'LIGHT BROWN YELLOW': 'FANCY LIGHT BROWN YELLOW',
            'VIVID ORANGY YELLOW': 'FANCY VIVID ORANGY YELLOW',
            'INTENSE YELLOW': 'FANCY INTENSE YELLOW',
            'vivid yellow': 'FANCY VIVID YELLOW',
            'intense yellow': 'FANCY INTENSE YELLOW',
            'light yellow': 'FANCY LIGHT YELLOW',
            'LIGHT BLUE': 'FANCY LIGHT BLUE',
            'ORANGY YELLOW': 'FANCY ORANGY YELLOW',
            'ht yellow': 'FANCY YELLOW',
            'LIGHT PINK': 'FANCY LIGHT PINK',
            'yellow light': 'FANCY LIGHT YELLOW',
            'yellow-green': 'FANCY YELLOW-GREEN',
            'GREEN YELLOW':'FANCY GREEN YELLOW',
            'lightgreenish yellow': 'FANCY LIGHT GREENISH YELLOW',
            'INTENSEGREENISH YELLOW': 'FANCY INTENSEGREENISH YELLOW',
            'INTENSE GREEN-YELLOW':'FANCY INTENSE GREEN-YELLOW',
            'grayishgreenish yellow': 'FANCY GRAYISH GREENISH YELLOW',
            'brownishgreenish yellow': 'FANCY BROWNISH GREENISH YELLOW',
            'LIGHT BROWN-PINK': 'FANCY LIGHT BROWN-PINK',
            'DARKPINK-BROWN':' FANCY DARKPINK-BROWN',
            'LIGHT PINK-BROWN,':'FANCY LIGHT PINK-BROWN',
            'LIGHTBROWNISH PINK': 'FANCY LIGHTBROWNISH PINK',
            'brownish yellow': 'FANCY BROWNISH YELLOW',
            'brown yellow': 'FANCY BROWNISH YELLOW',
            'brownishorangy yellow': 'FANCY BROWNISH ORANGY YELLOW',
            'BROWN-GREENISH YELLOW':'FANCY BROWN-GREENISH YELLOW',
            'darkbrown-yellow': 'FANCY DARK BROWN-YELLOW',
            'purplish pink': 'FANCY PURPLISH PINK',
            'light yellowishbrown': 'FANCY LIGHT YELLOWISH BROWN',
            'Brownish Orangy YellowNatural': 'FANCY BROWNISH ORANGY YELLOW',
            'lightpinkish brown': 'FANCY LIGHTPINKISH BROWN',
            'LIGHT BROWNISHYELLOW':' FANCY LIGHT BROWNISH YELLOW',
            'PINKISH BROWN':'FAINT PINKISH BROWN',
            'gray even': 'FANCY GRAY',
            'vividorangy yellow': 'FANCY VIVID ORANGY YELLOW',
            'brownish yellowvs1': 'FANCY BROWNISH YELLOW VS1',
            'dark yellowishbrown': 'FANCY DARK YELLOWISH BROWN',
            'pinkish brown': 'FANCY PINKISH BROWN',
            'pink-browneven': 'FANCY PINK-BROWN EVEN',
            'light yellowishgreen': 'FANCY LIGHT YELLOWISH GREEN',
            'pink purple': 'FANCY PINK PURPLE',
            'purplish pinksi1': 'FANCY PURPLISH PINK',
            'orangy pink': 'FANCY ORANGY PINK',
            'ORANGY BROWN':'FANCY ORANGY BROWN',
            ' intenseyellowish green': 'FANCY INTENSE YELLOWISH GREEN',
            'dark yellowishbrown': 'FANCY DARK YELLOWISH BROWN',
            'intenseyellowish green': 'FANCY INTENSE YELLOWISH GREEN',
            'brownish yellowgia': 'FANCY BROWNISH YELLOW',
            'deep pink': 'FANCY DEEP PINK',
            'light green': 'FANCY LIGHT GREEN',
            'purple-pink': 'FANCY PURPLE-PINK',
            'intense yellowvvs2': 'FANCY INTENSE YELLOWVVS2',
            'gray-blue': 'FANCY GRAY-BLUE',
            'green-yellow': 'FANCY GREEN-YELLOW',
            'vivid yellowvs1': 'FANCY VIVID YELLOWVS1',
            'fancypink-purple': 'FANCY FANCY PINK-PURPLE',
            'vivid yelloworange': 'FANCY VIVID YELLOWORANGE',
            'vivid orangyyellow': 'FANCY VIVID ORANGYYELLOW',
            'fancyyellow-green': 'FANCY FANCY YELLOW-GREEN',
            'pinkish purple': 'FANCY PINKISH PURPLE',
            'LIGHT PINKISHBROWN': 'FANCY LIGHT PINKISHBROWN',
            'faint brown': 'FANCY FAINT BROWN',
            'orange-brown': 'FANCY ORANGE-BROWN',
            'brown pink': 'FANCY BROWN PINK',
            'light yellow': 'FANCY LIGHT YELLOW',
            'intenseyellow orange': 'FANCY INTENSEYELLOW ORANGE',
            'brown pink': 'FANCY BROWN PINK',
            'yellow-brown': 'FANCY YELLOW-BROWN',
            'deep yellow': 'FANCY DEEP YELLOW',
            'orange brown': 'FANCY ORANGE BROWN',
            'FancyYellowish Orange': 'FANCY YELLOWISH ORANGE',
            'brownish greenish': 'FANCY BROWNISH GREENISH',
            'brown pink': 'FANCY BROWN PINK',
            'YELLOWISH GREEN': 'FANCY YELLOWISH GREEN',
            'Light YellowGIA': 'Fancy Light YellowGIA',
            'Dark OrangyBrown': 'Fancy Dark OrangyBrown',
            'intense pink': 'FANCY INTENSE PINK',
            'Pinkesh Purpale': 'Fancy Pinkesh Purpale',
            'LightYellowish Green': 'Fancy LightYellowish Green',
            'BROWN PURPLE': 'FANCY BROWN PURPLE',
            'brownish yellowvs2': 'FANCY BROWNISH YELLOWVS2',
            'FANCY YELLOWNATURAL': 'FANCY YELLOW ',
            'fancy pink': 'FANCY PINK',
            'PURPLEPINK': 'FANCY PURPLE PINK',
            'YellowNatural': 'FANCY YELLOW',
            'NFLY-Gr': 'Fancy Light Yellow-Green',
            'brownish pink': 'FANCY BROWNISH PINK',
            'Brownish YellowNatural': 'FANCY BROWNISH YELLOW',
            'NFLGr-Y': 'Fancy Light Green-Yellow',
            'light brown': 'FANCY LIGHT BROWN',
            'dark brown': 'FANCY DARK BROWN',
            'light gray': 'FANCY LIGHT GRAY',
            'dark gray': 'FANCY DARK GRAY',
            'deep yellow': 'FANCY DEEP YELLOW',
            'fance yellow': 'FANCY YELLOW',
            "Fancy YellowGIA": "FANCY YELLOW",
            'fly': 'FANCY LIGHT YELLOW',
            'fiy': 'FANCY LIGHT YELLOW',
            'fy': 'FANCY YELLOW',
            'htyellow': 'FANCY YELLOW',
            'yellowif': 'FANCY YELLOW',
            'orangypink': 'FANCY ORANGY PINK',
            'fancyyellow': 'FANCY YELLOW',
            'yellowsi2': 'FANCY YELLOWSI2',
            'greenishyellow': 'FANCY GREENISHYELLOW',
            'fancyyellow,': 'FANCY FANCY YELLOW',
            'GreenSI1': 'FANCY GREENS',
            'NFYE': 'FANCY NFYE',
            'BROWNORANGE': 'FANCY BROWNORANGE',
            'DEEPBROWN': 'FANCY DEEPBROWN',
            'ORANGEBROWN': 'FANCY ORANGE BROWN',
            'BROWNPINK': 'FANCY BROWNPINK',
            'LIGHTPINK': 'FANCY LIGHTPINK',
            'lightpink': 'FANCY LIGHT PINK',
            'brownsi2': 'FANCY BROWNSI2',
            'YELLOWBROWN': 'FANCY YELLOWBROWN',
            'intenseyellow': 'FANCY INTENSE YELLOW',
            'FVY': 'Fancy Vivid Yellow',
            'yellow': 'FANCY YELLOW',
            'vividyellow': 'FANCY VIVID YELLOW',
            'yeloow': 'FANCY YELLOW',
            'brown': 'FANCY BROWN',
            'yellowvvs1': 'FANCY YELLOW',
            'lightgreen': 'FANCY LIGHT GREEN',
            'yellowvs2': 'FANCY YELLOW',
            'yelloweven': 'FANCY YELLOW',
            'fanceyellow': 'FANCY YELLOW',
            'GREEN': 'FANCY GREEN',
            'pink': 'FANCY PINK',
            'gray': 'FANCY GRAY',
            'lightyellow': 'LIGHT YELLOW',
            'fancy yellow': 'FANCY YELLOW',
            'pinkish': 'FANCY PINK',
            'brownish pink': 'FANCY BROWNISH PINK',
            'green': 'FANCY GREEN',
            'blue': 'FANCY BLUE',   
            'Inte Yell':'Fancy Intense Yellow',
            'Brow Yell':'Fancy Brown Yellow',
            'Bro Yell':'Fancy Brown Yellow',
            'VIVID ORANGE YELLOW1':'Fancy Vivid Orange Yellow',
            'Viv Yell':'Fancy Vivid Yellow',
             'deep brownish greenish yellow': 'FANCY DEEP BROWNISH GREENISH YELLOW',
        'deep grayish yellow dish green': 'FANCY DEEP GRAYISH YELLOWISH GREEN',
        'light grayish greenish yellow': 'FANCY LIGHT GRAYISH GREENISH YELLOW',
        'naturalfancy brownish greenish yeiiow': 'FANCY BROWNISH GREENISH YELLOW ',
        'deep brownish purple-pink': 'FANCY DEEP BROWNISH PURPLE-PINK',
        'deep brownish purple pink': 'FANCY DEEP BROWNISH PURPLE PINK',
        'DEEP BROWNISH YELLOWISH ORANGE,': 'FANCY DEEP BROWNISH YELLOWISH ORANGE',
        'DEEP GREEN TREATED COLOUR': 'FANCY DEEP GREEN TREATED COLOUR',
        'Deep Brownish Yellowish Orange': 'Fancy Deep Brownish Yellowish Orange',
        'fancy light yellow': 'FANCY LIGHT YELLOW',
        'intense yellow-green': 'FANCY INTENSE YELLOW-GREEN',
        'lightbrownish greenish yellow': 'FANCY LIGHT BROWNISH GREENISH YELLOW',
        'darkbrown-greenish yellow': 'FANCY DARK BROWN-GREENISH YELLOW',
        'deep brownish yellow': 'FANCY DEEP BROWNISH YELLOW',
        'deep orangy yellow': 'FANCY DEEP ORANGY YELLOW',
        'deep brownish orangey yellow': 'FANCY DEEP BROWNISH ORANGY YELLOW',
        'intense purplish pink': 'FANCY INTENSE PURPLISH PINK',
        'lightgrayish greenish yellow': 'FANCY LIGHT GRAYISH GREENISH YELLOW',
        'dark orangey brown': 'FANCY DARK ORANGEY BROWN',
        'intense orange yellow': 'FANCY INTENSE ORANGE YELLOW',
        'light brownish greenish yellow': 'FANCY LIGHT BROWNISH GREENISH YELLOW',
        'light yellowishbrown': 'FANCY LIGHT YELLOWISH BROWN',
        'lightpinkish brown': 'FANCY LIGHTPINKISH BROWN',
        'brownish greenish yellownatural even': 'FANCY BROWNISH GREENISH YELLOW NATURAL',
        'light brownish greenishyellow': 'FANCY LIGHT BROWNISH GREENISH YELLOW',
        'gray-greenish yellow': 'FANCY GRAY-GREENISH YELLOW',
        'brownish greenish yellownatural': 'FANCY BROWNISH GREENISH YELLOW',
        'vivid orange yellow': 'FANCY VIVID ORANGE YELLOW',
        'deep brownish orange': 'FANCY DEEP BROWNISH ORANGE',
        'deep yellowish orange': 'FANCY DEEP YELLOWISH ORANGE',
        'brownish orangy pink': 'FANCY BROWNISH ORANGY PINK',
        'intense yellowish orange': 'FANCY INTENSE YELLOWISH ORANGE',
        'grayish yellowish green': 'FANCY GRAYISH YELLOWISH GREEN',
        'deep  pink-purple': 'FANCY DEEP PINK-PURPLE',
        'vivid yellowish orange ': 'FANCY VIVID YELLOWISH ORANGE',
        'intense yellowish green': 'FANCY INTENSE YELLOWISH GREEN',
        'deep brownish orangyyellow': 'FANCY BROWNISH ORANGY YELLOW',
        'dark orangy browneven': 'FANCY DARK ORANGY BROWN',
        'brownish purple-pink': 'FANCY BROWNISH PURPLE-PINK',
        'light pinkish purple': 'FANCY LIGHT PINKISH PURPLE',
        'deep yellowish- orangesi': 'FANCY DEEP YELLOWISH ORANGESI',
        'deep grayish greenishyellow': 'FANCY DEEP GRAYISH GREENISHYELLOW',
        'fancy pinkish purple': 'FANCY FANCY PINKISH PURPLE',
        'brownish greenish yellow': 'FANCY BROWNISH GREENISH YELLOW',
        'light greenish yellow': 'FANCY LIGHT GREENISH YELLOW',
        'dark orangy brown': 'FANCY DARK ORANGY BROWN',
        'light yellow green': 'FANCY LIGHT YELLOW GREEN',
        'darkgray yellowish green': 'FANCY DARKGRAY YELLOWISH GREEN',
        'dark orange-brown': 'FANCY DARK ORANGE-BROWN',
        'intense orangy yellow': 'FANCY INTENSE ORANGY YELLOW',
        'brownish purplish pink': 'FANCY BROWNISH PURPLISH PINK',
        'brownish-greenish yellow': 'FANCY BROWNISH-GREENISH YELLOW',
        'grayish greenish yellow': 'FANCY GRAYISH GREENISH YELLOW',
        'dark green gray': 'FANCY DARK GREEN GRAY',
        'VERY LIGHT PINK': 'FANCY VERY LIGHT PINK',
        
        'VIVID YELLOW ORANGE': 'FANCY VIVID YELLOW ORANGE',
        
        'INTENSE YELLOW ORANGE': 'FANCY INTENSE YELLOW ORANGE',
        'LIGHT YELLOWISH BROWN': 'FANCY LIGHT YELLOWISH BROWN',
        

        'deep orange yellow': 'FANCY DEEP ORANGE YELLOW',
        'DEEP GREEN-YELLOW':'FANCY DEEP GREEN-YELLOW',
        'light pinkish brown': 'FANCY LIGHT PINKISH BROWN',
        'dark gray yellowishgreen': 'FANCY DARK GRAY YELLOWISHGREEN',
        'light green yellow': 'FANCY LIGHT GREEN YELLOW',
        'light yellow green': 'FANCY LIGHT YELLOW GREEN',
        'DEEPBROWNISH YELLOWISH ORANGE': 'FANCY DEEPBROWNISH YELLOWISH ORANGE',
        'FancyGrayish Yellowish Gree': 'FancyGrayish Yellowish Gree',
        'DEEP BROWNISHYELLOWISH ORANGE': 'FANCY DEEP BROWNISHYELLOWISH ORANGE',
        'LIGHT BLUISH GREEN': 'FANCY LIGHT BLUISH GREEN',
        'LIGHT PINK': 'FANCY LIGHT PINK',
        'INTENSE BLUE': 'FANCY INTENSE BLUE',
        'PINKISH PURPLE': 'FANCY PINKISH PURPLE',
        'PINK PURPLE': 'FANCY PINK PURPLE',
        'PINK BROWN': 'FANCY PINK BROWN',
        'INTENSE YELLOW ORANGE': 'FANCY INTENSE YELLOW ORANGE',
        'DEEP BROWNISH ORANGY YELLOW': 'FANCY DEEP BROWNISH ORANGY YELLOW',
        'DEEP BLUISH GREEN': 'FANCY DEEP BLUISH GREEN',
        'VIVID YELLOW-ORANGE': 'FANCY VIVID YELLOW-ORANGE',
        'VERY LIGHT GREEN': 'FANCY VERY LIGHT GREEN',
        'VIVID PURPLISH PINK': 'FANCY VIVID PURPLISH PINK',
        'YELLOWISH GREEN': 'FANCY YELLOWISH GREEN',
        'VERY LIGHT YELLOW GREEN': 'FANCY VERY LIGHT YELLOW GREEN',
        'LIGHT PINK-BROWN': 'FANCY LIGHT PINK-BROWN',
        'MEDIUM BLUE': 'FANCY MEDIUM BLUE',
        'VIVID BLUE,': 'FANCY VIVID BLUE',
        'VIVID BLUE': 'FANCY VIVID BLUE',
        'LIGHT BROWN YELLOW': 'FANCY LIGHT BROWN YELLOW',
        'VIVID ORANGY YELLOW': 'FANCY VIVID ORANGY YELLOW',
        'INTENSE YELLOW': 'FANCY INTENSE YELLOW',
        'vivid yellow': 'FANCY VIVID YELLOW',
        'intense yellow': 'FANCY INTENSE YELLOW',
        'light yellow': 'FANCY LIGHT YELLOW',
        'LIGHT BLUE': 'FANCY LIGHT BLUE',
        'ORANGY YELLOW': 'FANCY ORANGY YELLOW',
        'ht yellow': 'FANCY YELLOW',
        'LIGHT PINK': 'FANCY LIGHT PINK',
        'yellow light': 'FANCY LIGHT YELLOW',
        'yellow-green': 'FANCY YELLOW-GREEN',
        'GREEN YELLOW':'FANCY GREEN YELLOW',
        'lightgreenish yellow': 'FANCY LIGHT GREENISH YELLOW',
        'INTENSEGREENISH YELLOW': 'FANCY INTENSEGREENISH YELLOW',
        'INTENSE GREEN-YELLOW':'FANCY INTENSE GREEN-YELLOW',
        'grayishgreenish yellow': 'FANCY GRAYISH GREENISH YELLOW',
        'brownishgreenish yellow': 'FANCY BROWNISH GREENISH YELLOW',
        'LIGHT BROWN-PINK': 'FANCY LIGHT BROWN-PINK',
        'DARKPINK-BROWN':' FANCY DARKPINK-BROWN',
        'LIGHT PINK-BROWN,':'FANCY LIGHT PINK-BROWN',
        'LIGHTBROWNISH PINK': 'FANCY LIGHTBROWNISH PINK',
        'brownish yellow': 'FANCY BROWNISH YELLOW',
        'brown yellow': 'FANCY BROWNISH YELLOW',
        'brownishorangy yellow': 'FANCY BROWNISH ORANGY YELLOW',
        'BROWN-GREENISH YELLOW':'FANCY BROWN-GREENISH YELLOW',
        'darkbrown-yellow': 'FANCY DARK BROWN-YELLOW',
        'purplish pink': 'FANCY PURPLISH PINK',
        'light yellowishbrown': 'FANCY LIGHT YELLOWISH BROWN',
        'Brownish Orangy YellowNatural': 'FANCY BROWNISH ORANGY YELLOW',
        'lightpinkish brown': 'FANCY LIGHTPINKISH BROWN',
        'LIGHT BROWNISHYELLOW':' FANCY LIGHT BROWNISH YELLOW',
        'PINKISH BROWN':'FAINT PINKISH BROWN',
        'gray even': 'FANCY GRAY',
        'vividorangy yellow': 'FANCY VIVID ORANGY YELLOW',
        'brownish yellowvs1': 'FANCY BROWNISH YELLOW VS1',
        'dark yellowishbrown': 'FANCY DARK YELLOWISH BROWN',
        'pinkish brown': 'FANCY PINKISH BROWN',
        'pink-browneven': 'FANCY PINK-BROWN EVEN',
        'light yellowishgreen': 'FANCY LIGHT YELLOWISH GREEN',
        'pink purple': 'FANCY PINK PURPLE',
        'purplish pinksi1': 'FANCY PURPLISH PINK',
        'orangy pink': 'FANCY ORANGY PINK',
        'ORANGY BROWN':'FANCY ORANGY BROWN',
        ' intenseyellowish green': 'FANCY INTENSE YELLOWISH GREEN',
        'dark yellowishbrown': 'FANCY DARK YELLOWISH BROWN',
        'intenseyellowish green': 'FANCY INTENSE YELLOWISH GREEN',
        'brownish yellowgia': 'FANCY BROWNISH YELLOW',
        'deep pink': 'FANCY DEEP PINK',
        'light green': 'FANCY LIGHT GREEN',
        'purple-pink': 'FANCY PURPLE-PINK',
        'intense yellowvvs2': 'FANCY INTENSE YELLOWVVS2',
        'gray-blue': 'FANCY GRAY-BLUE',
        'green-yellow': 'FANCY GREEN-YELLOW',
        'vivid yellowvs1': 'FANCY VIVID YELLOWVS1',
        'fancypink-purple': 'FANCY FANCY PINK-PURPLE',
        'vivid yelloworange': 'FANCY VIVID YELLOWORANGE',
        'vivid orangyyellow': 'FANCY VIVID ORANGYYELLOW',
        'fancyyellow-green': 'FANCY FANCY YELLOW-GREEN',
        'pinkish purple': 'FANCY PINKISH PURPLE',
        'LIGHT PINKISHBROWN': 'FANCY LIGHT PINKISHBROWN',
        'faint brown': 'FANCY FAINT BROWN',
        'orange-brown': 'FANCY ORANGE-BROWN',
        'brown pink': 'FANCY BROWN PINK',
        'light yellow': 'FANCY LIGHT YELLOW',
        'intenseyellow orange': 'FANCY INTENSEYELLOW ORANGE',
        'brown pink': 'FANCY BROWN PINK',
        'yellow-brown': 'FANCY YELLOW-BROWN',
        'deep yellow': 'FANCY DEEP YELLOW',
        'orange brown': 'FANCY ORANGE BROWN',
        'FancyYellowish Orange': 'FANCY YELLOWISH ORANGE',
        'brownish greenish': 'FANCY BROWNISH GREENISH',
        'brown pink': 'FANCY BROWN PINK',
        'YELLOWISH GREEN': 'FANCY YELLOWISH GREEN',
        'Light YellowGIA': 'Fancy Light YellowGIA',
        'Dark OrangyBrown': 'Fancy Dark OrangyBrown',
        'intense pink': 'FANCY INTENSE PINK',
        'Pinkesh Purpale': 'Fancy Pinkesh Purpale',
        'LightYellowish Green': 'Fancy LightYellowish Green',
        'BROWN PURPLE': 'FANCY BROWN PURPLE',
        'brownish yellowvs2': 'FANCY BROWNISH YELLOWVS2',
        'FANCY YELLOWNATURAL': 'FANCY YELLOW ',
        'fancy pink': 'FANCY PINK',
        'PURPLEPINK': 'FANCY PURPLE PINK',
        'YellowNatural': 'FANCY YELLOW',
        'NFLY-Gr': 'Fancy Light Yellow-Green',
        'brownish pink': 'FANCY BROWNISH PINK',
        'Brownish YellowNatural': 'FANCY BROWNISH YELLOW',
        'NFLGr-Y': 'Fancy Light Green-Yellow',
        'light brown': 'FANCY LIGHT BROWN',
        'dark brown': 'FANCY DARK BROWN',
        'light gray': 'FANCY LIGHT GRAY',
        'dark gray': 'FANCY DARK GRAY',
        'deep yellow': 'FANCY DEEP YELLOW',
        'fance yellow': 'FANCY YELLOW',
        "Fancy YellowGIA": "FANCY YELLOW",
        'fly': 'FANCY LIGHT YELLOW',
        'fiy': 'FANCY LIGHT YELLOW',
        'fy': 'FANCY YELLOW',
        'htyellow': 'FANCY YELLOW',
        'yellowif': 'FANCY YELLOW',
        'orangypink': 'FANCY ORANGY PINK',
        'fancyyellow': 'FANCY YELLOW',
        'yellowsi2': 'FANCY YELLOWSI2',
        'greenishyellow': 'FANCY GREENISHYELLOW',
        'fancyyellow,': 'FANCY FANCY YELLOW',
        'GreenSI1': 'FANCY GREENS',
        'NFYE': 'FANCY NFYE',
        'BROWNORANGE': 'FANCY BROWNORANGE',
        'DEEPBROWN': 'FANCY DEEPBROWN',
        'ORANGEBROWN': 'FANCY ORANGE BROWN',
        'BROWNPINK': 'FANCY BROWNPINK',
        'LIGHTPINK': 'FANCY LIGHTPINK',
        'lightpink': 'FANCY LIGHT PINK',
        'brownsi2': 'FANCY BROWNSI2',
        'YELLOWBROWN': 'FANCY YELLOWBROWN',
        'intenseyellow': 'FANCY INTENSE YELLOW',
        'FVY': 'Fancy Vivid Yellow',
        'yellow': 'FANCY YELLOW',
        'vividyellow': 'FANCY VIVID YELLOW',
        'yeloow': 'FANCY YELLOW',
        'brown': 'FANCY BROWN',
        'yellowvvs1': 'FANCY YELLOW',
        'lightgreen': 'FANCY LIGHT GREEN',
        'yellowvs2': 'FANCY YELLOW',
        'yelloweven': 'FANCY YELLOW',
        'fanceyellow': 'FANCY YELLOW',
        'GREEN': 'FANCY GREEN',
        'pink': 'FANCY PINK',
        'gray': 'FANCY GRAY',
        'lightyellow': 'LIGHT YELLOW',
        'fancy yellow': 'FANCY YELLOW',
        'pinkish': 'FANCY PINK',
        'brownish pink': 'FANCY BROWNISH PINK',
        'green': 'FANCY GREEN',
        'blue': 'FANCY BLUE',

        } 

clarity={
        'P1': 'I1', 'P2': 'I2', 'P3': 'I3', 'P.1': 'I1', 'P.2': 'I2', 'P.3': 'I3',
        'LC': 'IF', 'LOUPE CLEAN': 'IF', 'LOUPE-CLEAN': 'IF',
        'P1': 'I1', 'P2': 'I2', 'P3': 'I3', 'P.1': 'I1', 'P.2': 'I2', 'P.3': 'I3',
        'LC': 'IF', 'LOUPE CLEAN': 'IF', 'LOUPE-CLEAN': 'IF',
        'VVSI': 'VVS1',
        'VV': 'VVS1',
        'VC1': 'VVS1',
        'VC2': 'VVS2',
        'VV1': 'VVS1',
        'VV2': 'VVS2',
        'INTERNALLY FLAWLESS': 'IF',
        'INTERNALLY FALWLESSGIA': 'IF',
        'FLAWLESS': 'FL',
        'LC': 'IF',
        'VVS-1': 'VVS1',
        'VVS-2': 'VVS2',
        'VS-1': 'VS1',
        'VS-2': 'VS2',
        'SI-1': 'SI1',
        'SI-2': 'SI2',
        'SI-3': 'SI3',
        # Dotted notation
        'I.1': 'I1',
        'I.2': 'I2',
        'I.3': 'I3',
        'VS.1': 'VS1',
        'VS.2': 'VS2',
        'VVS.1': 'VVS1',
        'VVS.2': 'VVS2',
        'SI.1': 'SI1',
        'SI.2': 'SI2',
        'SI.3': 'SI3',
        'I.F.': 'IF',
        'FLALESS': 'FL',
        'VSI': 'VS1',

        'S1': 'SI1',
        'S2': 'SI2',
        'S3': 'SI3',
        'V1': 'VVS1',
        'V2': 'VVS2',
        'S12': 'SI2',
        'VVS': 'VVS2',
        'VS': 'VS2',
        'SI': 'SI1',
        'VV': 'VVS2',
        'SI1': 'SI1', 'SI2': 'SI2', 'SI3': 'SI3',
        'VS1': 'VS1', 'VS2': 'VS2',
        'VVS1': 'VVS1', 'VVS2': 'VVS2',
        'P1': 'I1', 'P2': 'I2', 'P3': 'I3', 'P.1': 'I1', 'P.2': 'I2', 'P.3': 'I3',
        'LC': 'IF', 'LOUPE CLEAN': 'IF', 'LOUPE-CLEAN': 'IF'
        }
    
lab={
        'GIA': 'GIA', 'CERT NO.GIA': 'GIA',
        'IGI': 'IGI', 'DIGI': 'IGI', 'FIGI': 'IGI', 'GIGI': 'IGI', 'HIGI': 'IGI',
        'HRD': 'HRD', 'FHRD': 'HRD', 'GHRD': 'HRD', 'HHRD': 'HRD',
        'GSI': 'GSI'

        }
           
                
